[tox]
envlist = lint,unit,integ,load
skipsdist = true
requires = tox>=4.0

[testenv]
passenv = *
setenv =
    POETRY = poetry
skip_install = true
deps =
    poetry==1.8.3
allowlist_externals =
    make
    docker
commands_pre =
    poetry -C services/gateway install --with dev
    poetry -C services/safe_evaluator install --with dev

[testenv:lint]
commands =
    make lint

[testenv:unit]
commands =
    make unit

[testenv:integ]
commands =
    make integration

[testenv:load]
commands =
    make load-test
